### PR TITLE
adapt event payload to aframe 0.4.0 cursor component

### LINKED ISSUE #5: cursor events don't match aframe cursor component
As this component basically duplicates aframe's internal [`cursor` component](https://github.com/aframevr/aframe/blob/master/src/components/cursor.js) (both in terms of functionality and code), it should emit the same events, and more importantly, the same event-payloads.

aframe's cursor event payload changed in 0.4.0 through [this commit](https://github.com/aframevr/aframe/commit/d5f88f46477f68d2a82642b047ec827816c2ae7c), adding the `intersection` attribute, which contains important data such as the position of intersection.

I adapted this change to the `vive-cursor` component [here](https://github.com/crend02/GeoVR/blob/master/src/vive-cursor.js) and can send a PR. (this introduces no breaking changes).

In the long run, one should think about a way to avoid the code duplication, and somehow inherit the cursor components behaviour.

### PR DESCRIPTION
**Pull request by noerw**
adding the `intersection` property to all events. code copied from [aframe/cursor.js](https://github.com/aframevr/aframe/blob/master/src/components/cursor.js)
fixes #5

### CODE REVIEW

**Comment by bryik** [comment]
Thanks! I'll look at this as soon as I have the time (probably Saturday).

**Comment by bryik** [comment]
All right, looks good. Thanks again!

**Comment by noerw** [comment]
can you bump the version and make a new npm release?

**Comment by bryik** [comment]
Yep. Looks like I bumped last week but neglected to push and republish. It's done now.

**Pull request merged**
